language: android
jdk:
    - oraclejdk8
sudo: required
android:
    components:
        - tools
        - tools
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services
        - build-tools-23.0.3
        - android-24
        - sys-img-armeabi-v7a-android-24 # 7.0
    licenses:
        - '.+'
before_install:
    - chmod +x gradlew
#before_script:
#    - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
#    - emulator -avd test -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyevent 82 &
script:
    - ./gradlew build connectedCheck --stacktrace
notifications:
    on_success: change
    on_failure: never